/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OgRouteImport } from './routes/og'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125404RouteImport } from './routes/{-$locale}/404'
import { Route as Char123LocaleChar125SplatRouteImport } from './routes/{-$locale}/$'
import { Route as Char123LocaleChar125appRouteRouteImport } from './routes/{-$locale}/(app)/route'
import { Route as Char123LocaleChar125appIndexRouteImport } from './routes/{-$locale}/(app)/index'
import { Route as Char123LocaleChar125appOptimizeRouteImport } from './routes/{-$locale}/(app)/optimize'
import { Route as Char123LocaleChar125appAboutRouteImport } from './routes/{-$locale}/(app)/about'
import { Route as Char123LocaleChar125appBlogRouteRouteImport } from './routes/{-$locale}/(app)/blog/route'
import { Route as Char123LocaleChar125appBlogIndexRouteImport } from './routes/{-$locale}/(app)/blog/index'
import { Route as Char123LocaleChar125appBlogSlugRouteImport } from './routes/{-$locale}/(app)/blog/$slug'

const OgRoute = OgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125404Route = Char123LocaleChar125404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => Char123LocaleChar125RouteRoute,
} as any)
const Char123LocaleChar125SplatRoute =
  Char123LocaleChar125SplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125appRouteRoute =
  Char123LocaleChar125appRouteRouteImport.update({
    id: '/(app)',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125appIndexRoute =
  Char123LocaleChar125appIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125appRouteRoute,
  } as any)
const Char123LocaleChar125appOptimizeRoute =
  Char123LocaleChar125appOptimizeRouteImport.update({
    id: '/optimize',
    path: '/optimize',
    getParentRoute: () => Char123LocaleChar125appRouteRoute,
  } as any)
const Char123LocaleChar125appAboutRoute =
  Char123LocaleChar125appAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => Char123LocaleChar125appRouteRoute,
  } as any)
const Char123LocaleChar125appBlogRouteRoute =
  Char123LocaleChar125appBlogRouteRouteImport.update({
    id: '/blog',
    path: '/blog',
    getParentRoute: () => Char123LocaleChar125appRouteRoute,
  } as any)
const Char123LocaleChar125appBlogIndexRoute =
  Char123LocaleChar125appBlogIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125appBlogRouteRoute,
  } as any)
const Char123LocaleChar125appBlogSlugRoute =
  Char123LocaleChar125appBlogSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => Char123LocaleChar125appBlogRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125appRouteRouteWithChildren
  '/og': typeof OgRoute
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/{-$locale}/blog': typeof Char123LocaleChar125appBlogRouteRouteWithChildren
  '/{-$locale}/about': typeof Char123LocaleChar125appAboutRoute
  '/{-$locale}/optimize': typeof Char123LocaleChar125appOptimizeRoute
  '/{-$locale}/': typeof Char123LocaleChar125appIndexRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125appBlogSlugRoute
  '/{-$locale}/blog/': typeof Char123LocaleChar125appBlogIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}': typeof Char123LocaleChar125appIndexRoute
  '/og': typeof OgRoute
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/{-$locale}/about': typeof Char123LocaleChar125appAboutRoute
  '/{-$locale}/optimize': typeof Char123LocaleChar125appOptimizeRoute
  '/{-$locale}/blog/$slug': typeof Char123LocaleChar125appBlogSlugRoute
  '/{-$locale}/blog': typeof Char123LocaleChar125appBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/og': typeof OgRoute
  '/{-$locale}/(app)': typeof Char123LocaleChar125appRouteRouteWithChildren
  '/{-$locale}/$': typeof Char123LocaleChar125SplatRoute
  '/{-$locale}/404': typeof Char123LocaleChar125404Route
  '/{-$locale}/(app)/blog': typeof Char123LocaleChar125appBlogRouteRouteWithChildren
  '/{-$locale}/(app)/about': typeof Char123LocaleChar125appAboutRoute
  '/{-$locale}/(app)/optimize': typeof Char123LocaleChar125appOptimizeRoute
  '/{-$locale}/(app)/': typeof Char123LocaleChar125appIndexRoute
  '/{-$locale}/(app)/blog/$slug': typeof Char123LocaleChar125appBlogSlugRoute
  '/{-$locale}/(app)/blog/': typeof Char123LocaleChar125appBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/og'
    | '/{-$locale}/$'
    | '/{-$locale}/404'
    | '/{-$locale}/blog'
    | '/{-$locale}/about'
    | '/{-$locale}/optimize'
    | '/{-$locale}/'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}'
    | '/og'
    | '/{-$locale}/$'
    | '/{-$locale}/404'
    | '/{-$locale}/about'
    | '/{-$locale}/optimize'
    | '/{-$locale}/blog/$slug'
    | '/{-$locale}/blog'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/og'
    | '/{-$locale}/(app)'
    | '/{-$locale}/$'
    | '/{-$locale}/404'
    | '/{-$locale}/(app)/blog'
    | '/{-$locale}/(app)/about'
    | '/{-$locale}/(app)/optimize'
    | '/{-$locale}/(app)/'
    | '/{-$locale}/(app)/blog/$slug'
    | '/{-$locale}/(app)/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
  OgRoute: typeof OgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/og': {
      id: '/og'
      path: '/og'
      fullPath: '/og'
      preLoaderRoute: typeof OgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/404': {
      id: '/{-$locale}/404'
      path: '/404'
      fullPath: '/{-$locale}/404'
      preLoaderRoute: typeof Char123LocaleChar125404RouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/$': {
      id: '/{-$locale}/$'
      path: '/$'
      fullPath: '/{-$locale}/$'
      preLoaderRoute: typeof Char123LocaleChar125SplatRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(app)': {
      id: '/{-$locale}/(app)'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125appRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(app)/': {
      id: '/{-$locale}/(app)/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125appIndexRouteImport
      parentRoute: typeof Char123LocaleChar125appRouteRoute
    }
    '/{-$locale}/(app)/optimize': {
      id: '/{-$locale}/(app)/optimize'
      path: '/optimize'
      fullPath: '/{-$locale}/optimize'
      preLoaderRoute: typeof Char123LocaleChar125appOptimizeRouteImport
      parentRoute: typeof Char123LocaleChar125appRouteRoute
    }
    '/{-$locale}/(app)/about': {
      id: '/{-$locale}/(app)/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125appAboutRouteImport
      parentRoute: typeof Char123LocaleChar125appRouteRoute
    }
    '/{-$locale}/(app)/blog': {
      id: '/{-$locale}/(app)/blog'
      path: '/blog'
      fullPath: '/{-$locale}/blog'
      preLoaderRoute: typeof Char123LocaleChar125appBlogRouteRouteImport
      parentRoute: typeof Char123LocaleChar125appRouteRoute
    }
    '/{-$locale}/(app)/blog/': {
      id: '/{-$locale}/(app)/blog/'
      path: '/'
      fullPath: '/{-$locale}/blog/'
      preLoaderRoute: typeof Char123LocaleChar125appBlogIndexRouteImport
      parentRoute: typeof Char123LocaleChar125appBlogRouteRoute
    }
    '/{-$locale}/(app)/blog/$slug': {
      id: '/{-$locale}/(app)/blog/$slug'
      path: '/$slug'
      fullPath: '/{-$locale}/blog/$slug'
      preLoaderRoute: typeof Char123LocaleChar125appBlogSlugRouteImport
      parentRoute: typeof Char123LocaleChar125appBlogRouteRoute
    }
  }
}

interface Char123LocaleChar125appBlogRouteRouteChildren {
  Char123LocaleChar125appBlogSlugRoute: typeof Char123LocaleChar125appBlogSlugRoute
  Char123LocaleChar125appBlogIndexRoute: typeof Char123LocaleChar125appBlogIndexRoute
}

const Char123LocaleChar125appBlogRouteRouteChildren: Char123LocaleChar125appBlogRouteRouteChildren =
  {
    Char123LocaleChar125appBlogSlugRoute: Char123LocaleChar125appBlogSlugRoute,
    Char123LocaleChar125appBlogIndexRoute:
      Char123LocaleChar125appBlogIndexRoute,
  }

const Char123LocaleChar125appBlogRouteRouteWithChildren =
  Char123LocaleChar125appBlogRouteRoute._addFileChildren(
    Char123LocaleChar125appBlogRouteRouteChildren,
  )

interface Char123LocaleChar125appRouteRouteChildren {
  Char123LocaleChar125appBlogRouteRoute: typeof Char123LocaleChar125appBlogRouteRouteWithChildren
  Char123LocaleChar125appAboutRoute: typeof Char123LocaleChar125appAboutRoute
  Char123LocaleChar125appOptimizeRoute: typeof Char123LocaleChar125appOptimizeRoute
  Char123LocaleChar125appIndexRoute: typeof Char123LocaleChar125appIndexRoute
}

const Char123LocaleChar125appRouteRouteChildren: Char123LocaleChar125appRouteRouteChildren =
  {
    Char123LocaleChar125appBlogRouteRoute:
      Char123LocaleChar125appBlogRouteRouteWithChildren,
    Char123LocaleChar125appAboutRoute: Char123LocaleChar125appAboutRoute,
    Char123LocaleChar125appOptimizeRoute: Char123LocaleChar125appOptimizeRoute,
    Char123LocaleChar125appIndexRoute: Char123LocaleChar125appIndexRoute,
  }

const Char123LocaleChar125appRouteRouteWithChildren =
  Char123LocaleChar125appRouteRoute._addFileChildren(
    Char123LocaleChar125appRouteRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125appRouteRoute: typeof Char123LocaleChar125appRouteRouteWithChildren
  Char123LocaleChar125SplatRoute: typeof Char123LocaleChar125SplatRoute
  Char123LocaleChar125404Route: typeof Char123LocaleChar125404Route
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125appRouteRoute:
      Char123LocaleChar125appRouteRouteWithChildren,
    Char123LocaleChar125SplatRoute: Char123LocaleChar125SplatRoute,
    Char123LocaleChar125404Route: Char123LocaleChar125404Route,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
  OgRoute: OgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
