import { type Dictionary, t } from "intlayer";

const aboutContent: Dictionary = {
  key: "about",
  content: {
    title: t({
      en: "About Tiny SVG",
      zh: "关于 Tiny SVG",
      ko: "Tiny SVG 소개",
      de: "Über Tiny SVG",
      fr: "À propos de Tiny SVG",
    }),
    whatIsSection: {
      title: t({
        en: "What is Tiny SVG?",
        zh: "什么是 Tiny SVG？",
        ko: "Tiny SVG란 무엇인가요?",
        de: "Was ist Tiny SVG?",
        fr: "Qu'est-ce que Tiny SVG ?",
      }),
      description: t({
        en: "Tiny SVG is a powerful web-based SVG optimization tool that helps you compress and optimize your SVG files without any backend service. All processing happens right in your browser, ensuring your files remain private and secure.",
        zh: "Tiny SVG 是一个强大的基于 Web 的 SVG 优化工具，可帮助您在无需任何后端服务的情况下压缩和优化 SVG 文件。所有处理都在您的浏览器中进行，确保您的文件保持私密和安全。",
        ko: "Tiny SVG는 백엔드 서비스 없이 SVG 파일을 압축하고 최적화할 수 있는 강력한 웹 기반 SVG 최적화 도구입니다. 모든 처리는 브라우저에서 바로 이루어지므로 파일이 비공개로 안전하게 유지됩니다.",
        de: "Tiny SVG ist ein leistungsstarkes webbasiertes SVG-Optimierungstool, das Ihnen hilft, Ihre SVG-Dateien ohne Backend-Service zu komprimieren und zu optimieren. Die gesamte Verarbeitung erfolgt direkt in Ihrem Browser, sodass Ihre Dateien privat und sicher bleiben.",
        fr: "Tiny SVG est un puissant outil d'optimisation SVG basé sur le web qui vous aide à compresser et optimiser vos fichiers SVG sans aucun service backend. Tout le traitement se fait directement dans votre navigateur, garantissant que vos fichiers restent privés et sécurisés.",
      }),
    },
    featuresSection: {
      title: t({
        en: "Features",
        zh: "功能特性",
        ko: "기능",
        de: "Funktionen",
        fr: "Fonctionnalités",
      }),
      items: {
        compression: t({
          en: "Fast and efficient SVG compression using SVGO",
          zh: "使用 SVGO 进行快速高效的 SVG 压缩",
          ko: "SVGO를 사용한 빠르고 효율적인 SVG 압축",
          de: "Schnelle und effiziente SVG-Komprimierung mit SVGO",
          fr: "Compression SVG rapide et efficace avec SVGO",
        }),
        preview: t({
          en: "Real-time preview of original and optimized SVG",
          zh: "原始和优化后的 SVG 实时预览",
          ko: "원본 및 최적화된 SVG의 실시간 미리보기",
          de: "Echtzeitvorschau von Original- und optimierter SVG",
          fr: "Aperçu en temps réel du SVG original et optimisé",
        }),
        customizable: t({
          en: "Fully customizable optimization settings",
          zh: "完全可自定义的优化设置",
          ko: "완전히 맞춤 설정 가능한 최적화 설정",
          de: "Vollständig anpassbare Optimierungseinstellungen",
          fr: "Paramètres d'optimisation entièrement personnalisables",
        }),
        noServer: t({
          en: "No server required - all processing done in browser",
          zh: "无需服务器 - 所有处理均在浏览器中完成",
          ko: "서버 불필요 - 모든 처리가 브라우저에서 완료됨",
          de: "Kein Server erforderlich - alle Verarbeitung im Browser",
          fr: "Aucun serveur requis - tout le traitement se fait dans le navigateur",
        }),
        dragDrop: t({
          en: "Drag and drop support",
          zh: "支持拖放操作",
          ko: "드래그 앤 드롭 지원",
          de: "Drag & Drop-Unterstützung",
          fr: "Support du glisser-déposer",
        }),
        codeDiff: t({
          en: "Code diff viewer for before/after comparison",
          zh: "代码差异查看器，用于前后对比",
          ko: "전후 비교를 위한 코드 차이 뷰어",
          de: "Code-Diff-Viewer für Vorher/Nachher-Vergleich",
          fr: "Visualiser les différences de code avant/après optimisation",
        }),
      },
    },
    figmaPluginSection: {
      title: t({
        en: "Figma Plugin",
        zh: "Figma 插件",
        ko: "Figma 플러그인",
        de: "Figma Plugin",
        fr: "Plugin Figma",
      }),
      description: t({
        en: "Optimize SVGs directly in Figma with our official plugin! Available now on Figma Community, it brings all the power of Tiny SVG into your design workflow.",
        zh: "使用我们的官方插件直接在 Figma 中优化 SVG！现已在 Figma 社区上线，将 Tiny SVG 的所有功能带入您的设计工作流程。",
        ko: "공식 플러그인으로 Figma에서 직접 SVG를 최적화하세요! Figma 커뮤니티에서 이용 가능하며 Tiny SVG의 모든 기능을 디자인 워크플로우에 제공합니다.",
        de: "Optimieren Sie SVGs direkt in Figma mit unserem offiziellen Plugin! Jetzt in der Figma Community verfügbar, bringt es die gesamte Leistung von Tiny SVG in Ihren Design-Workflow.",
        fr: "Optimisez les SVG directement dans Figma avec notre plugin officiel ! Disponible dès maintenant sur Figma Community, il apporte toute la puissance de Tiny SVG à votre flux de travail de conception.",
      }),
      features: {
        batch: t({
          en: "Batch processing - optimize multiple SVG layers at once",
          zh: "批量处理 - 一次优化多个 SVG 图层",
          ko: "일괄 처리 - 여러 SVG 레이어를 한 번에 최적화",
          de: "Stapelverarbeitung - mehrere SVG-Ebenen auf einmal optimieren",
          fr: "Traitement par lots - optimisez plusieurs calques SVG à la fois",
        }),
        realtime: t({
          en: "Real-time preview with side-by-side diff viewer",
          zh: "实时预览，带有并排差异查看器",
          ko: "나란히 비교 뷰어로 실시간 미리보기",
          de: "Echtzeitvorschau mit Seite-an-Seite-Diff-Viewer",
          fr: "Aperçu en temps réel avec visualisation des différences côte à côte",
        }),
        presets: t({
          en: "Compression presets - Default, Aggressive, Minimal, Custom",
          zh: "压缩预设 - 默认、激进、最小、自定义",
          ko: "압축 프리셋 - 기본, 공격적, 최소, 사용자 정의",
          de: "Komprimierungsvorlagen - Standard, Aggressiv, Minimal, Benutzerdefiniert",
          fr: "Préréglages de compression - Par défaut, Agressif, Minimal, Personnalisé",
        }),
        replace: t({
          en: "In-place replacement - update SVGs directly in your designs",
          zh: "原位替换 - 直接在设计中更新 SVG",
          ko: "제자리 교체 - 디자인에서 직접 SVG 업데이트",
          de: "In-Place-Ersetzung - SVGs direkt in Ihren Designs aktualisieren",
          fr: "Remplacement sur place - mettez à jour les SVG directement dans vos designs",
        }),
        codeExport: t({
          en: "Code export - generate React, Vue, Svelte, React Native, Flutter code",
          zh: "代码导出 - 生成 React、Vue、Svelte、React Native、Flutter 代码",
          ko: "코드 내보내기 - React, Vue, Svelte, React Native, Flutter 코드 생성",
          de: "Code-Export - React-, Vue-, Svelte-, React Native-, Flutter-Code generieren",
          fr: "Export de code - générez du code React, Vue, Svelte, React Native, Flutter",
        }),
      },
      installButton: t({
        en: "Install from Figma Community",
        zh: "从 Figma 社区安装",
        ko: "Figma 커뮤니티에서 설치",
        de: "Von Figma Community installieren",
        fr: "Installer depuis Figma Community",
      }),
    },
    authorSection: {
      title: t({
        en: "Author",
        zh: "作者",
        ko: "작성자",
        de: "Autor",
        fr: "Auteur",
      }),
      createdBy: t({
        en: "Created by",
        zh: "作者",
        ko: "제작자",
        de: "Erstellt von",
        fr: "Créé par",
      }),
    },
    dependenciesSection: {
      title: t({
        en: "Built With",
        zh: "构建技术",
        ko: "기술 스택",
        de: "Erstellt mit",
        fr: "Construit avec",
      }),
      description: t({
        en: "This project is built with amazing open source libraries:",
        zh: "本项目使用了以下优秀的开源库构建：",
        ko: "이 프로젝트는 놀라운 오픈 소스 라이브러리로 구축되었습니다:",
        de: "Dieses Projekt wurde mit erstaunlichen Open-Source-Bibliotheken erstellt:",
        fr: "Ce projet est construit avec de fantastiques bibliothèques open source :",
      }),
      libraries: {
        svgo: t({
          en: "SVGO - SVG optimization library",
          zh: "SVGO - SVG 优化库",
          ko: "SVGO - SVG 최적화 라이브러리",
          de: "SVGO - SVG-Optimierungsbibliothek",
          fr: "SVGO - Bibliothèque d'optimisation SVG",
        }),
        router: t({
          en: "TanStack Router - Type-safe routing",
          zh: "TanStack Router - 类型安全的路由",
          ko: "TanStack Router - 타입 안전 라우팅",
          de: "TanStack Router - Typsicheres Routing",
          fr: "TanStack Router - Routage typé",
        }),
        start: t({
          en: "TanStack Start - Full-stack React framework",
          zh: "TanStack Start - 全栈 React 框架",
          ko: "TanStack Start - 풀스택 React 프레임워크",
          de: "TanStack Start - Full-Stack React Framework",
          fr: "TanStack Start - Framework React full-stack",
        }),
        react: t({
          en: "React - UI library",
          zh: "React - UI 库",
          ko: "React - UI 라이브러리",
          de: "React - UI-Bibliothek",
          fr: "React - Bibliothèque UI",
        }),
        intlayer: t({
          en: "Intlayer - Type-safe i18n library",
          zh: "Intlayer - 类型安全的国际化库",
          ko: "Intlayer - 타입 안전 국제화 라이브러리",
          de: "Intlayer - Typsichere i18n-Bibliothek",
          fr: "Intlayer - Bibliothèque i18n typée",
        }),
        radix: t({
          en: "Radix UI - Accessible component primitives",
          zh: "Radix UI - 无障碍组件基础库",
          ko: "Radix UI - 접근 가능한 컴포넌트 프리미티브",
          de: "Radix UI - Barrierefreie Komponenten-Primitiven",
          fr: "Radix UI - composants React accessibles et non stylisés",
        }),
        refractor: t({
          en: "Refractor - Lightweight syntax highlighting",
          zh: "Refractor - 轻量级语法高亮",
          ko: "Refractor - 경량 구문 강조",
          de: "Refractor - Leichtgewichtige Syntax-Hervorhebung",
          fr: "Refractor - Coloration syntaxique légère",
        }),
        prettier: t({
          en: "Prettier - Code formatter",
          zh: "Prettier - 代码格式化工具",
          ko: "Prettier - 코드 포맷터",
          de: "Prettier - Code-Formatierer",
          fr: "Prettier - Formateur de code",
        }),
        tailwind: t({
          en: "Tailwind CSS - Utility-first CSS framework",
          zh: "Tailwind CSS - 实用优先的 CSS 框架",
          ko: "Tailwind CSS - 유틸리티 우선 CSS 프레임워크",
          de: "Tailwind CSS - Utility-First-CSS-Framework",
          fr: "Tailwind CSS - Framework CSS utility-first",
        }),
        biome: t({
          en: "Biome - Fast linter and formatter",
          zh: "Biome - 快速的代码检查和格式化工具",
          ko: "Biome - 빠른 린터 및 포맷터",
          de: "Biome - Schneller Linter und Formatierer",
          fr: "Biome - Linter et formateur rapide",
        }),
        vite: t({
          en: "Vite - Build tool",
          zh: "Vite - 构建工具",
          ko: "Vite - 빌드 도구",
          de: "Vite - Build-Tool",
          fr: "Vite - Outil de build",
        }),
      },
    },
    openSourceSection: {
      title: t({
        en: "Open Source",
        zh: "开源",
        ko: "오픈 소스",
        de: "Open Source",
        fr: "Open Source",
      }),
      description: t({
        en: "This project is open source and available on GitHub. Contributions, bug reports, and feature requests are welcome!",
        zh: "本项目是开源的，可在 GitHub 上获取。欢迎贡献代码、报告错误和提出功能请求！",
        ko: "이 프로젝트는 오픈 소스이며 GitHub에서 사용할 수 있습니다. 기여, 버그 보고 및 기능 요청을 환영합니다!",
        de: "Dieses Projekt ist Open Source und auf GitHub verfügbar. Beiträge, Fehlerberichte und Feature-Anfragen sind willkommen!",
        fr: "Ce projet est open source et disponible sur GitHub. Les contributions, les rapports de bugs et les demandes de fonctionnalités sont les bienvenues !",
      }),
      viewOnGitHub: t({
        en: "View on GitHub",
        zh: "在 GitHub 上查看",
        ko: "GitHub에서 보기",
        de: "Auf GitHub ansehen",
        fr: "Voir sur GitHub",
      }),
    },
  },
};

export default aboutContent;
