import { type Dictionary, t } from "intlayer";

const optimizeContent = {
  key: "optimize",
  content: {
    title: t({
      en: "Optimize SVG",
      zh: "优化 SVG",
      ko: "SVG 최적화",
      de: "SVG optimieren",
      fr: "Optimiser SVG",
    }),
    header: {
      title: t({
        en: "Optimize SVG",
        zh: "优化 SVG",
        ko: "SVG 최적화",
        de: "SVG optimieren",
        fr: "Optimiser SVG",
      }),
      copy: t({
        en: "Copy",
        zh: "复制",
        ko: "복사",
        de: "Kopieren",
        fr: "Copier",
      }),
      download: t({
        en: "Download",
        zh: "下载",
        ko: "다운로드",
        de: "Herunterladen",
        fr: "Télécharger",
      }),
      reupload: t({
        en: "Reupload",
        zh: "重新上传",
        ko: "다시 업로드",
        de: "Erneut hochladen",
        fr: "Recharger",
      }),
      history: t({
        en: "History",
        zh: "历史记录",
        ko: "기록",
        de: "Verlauf",
        fr: "Historique",
      }),
    },
    history: {
      title: t({
        en: "History",
        zh: "历史记录",
        ko: "기록",
        de: "Verlauf",
        fr: "Historique",
      }),
      empty: t({
        en: "No saved SVGs yet",
        zh: "还没有保存的 SVG",
        ko: "저장된 SVG가 없습니다",
        de: "Noch keine gespeicherten SVGs",
        fr: "Aucun SVG enregistré",
      }),
      clearAll: t({
        en: "Clear All",
        zh: "清除全部",
        ko: "모두 지우기",
        de: "Alle löschen",
        fr: "Tout effacer",
      }),
      close: t({
        en: "Close",
        zh: "关闭",
        ko: "닫기",
        de: "Schließen",
        fr: "Fermer",
      }),
      delete: t({
        en: "Delete",
        zh: "删除",
        ko: "삭제",
        de: "Löschen",
        fr: "Supprimer",
      }),
      loadEntry: t({
        en: "Load SVG",
        zh: "加载 SVG",
        ko: "SVG 로드",
        de: "SVG laden",
        fr: "Charger SVG",
      }),
    },
    buttons: {
      copy: t({
        en: "Copy",
        zh: "复制",
        ko: "복사",
        de: "Kopieren",
        fr: "Copier",
      }),
      download: t({
        en: "Download",
        zh: "下载",
        ko: "다운로드",
        de: "Herunterladen",
        fr: "Télécharger",
      }),
    },
    tabs: {
      original: t({
        en: "Original",
        zh: "原始",
        ko: "원본",
        de: "Original",
        fr: "Original",
      }),
      optimized: t({
        en: "Optimized",
        zh: "已优化",
        ko: "최적화됨",
        de: "Optimiert",
        fr: "Optimisé",
      }),
      code: t({
        en: "Code",
        zh: "代码",
        ko: "코드",
        de: "Code",
        fr: "Code",
      }),
    },
    settings: {
      title: t({
        en: "Settings",
        zh: "设置",
        ko: "설정",
        de: "Einstellungen",
        fr: "Paramètres",
      }),
      global: {
        title: t({
          en: "Global Settings",
          zh: "全局设置",
          ko: "グローバル설정",
          de: "Globale Einstellungen",
          fr: "Paramètres globaux",
        }),
        showOriginal: t({
          en: "Show original",
          zh: "显示原始",
          ko: "원본を表示",
          de: "Original anzeigen",
          fr: "Afficher l'original",
        }),
        compareGzipped: t({
          en: "Compare gzipped",
          zh: "比较压缩后",
          ko: "Gzip 압축 비교",
          de: "Gzip-Komprimierung vergleichen",
          fr: "Comparer gzippé",
        }),
        prettifyMarkup: t({
          en: "Prettify markup",
          zh: "美化标记",
          ko: "마크업 정리",
          de: "Markup verschönern",
          fr: "Embellir le markup",
        }),
        multipass: t({
          en: "Multipass",
          zh: "多次优化",
          ko: "다중 패스",
          de: "Mehrfachdurchlauf",
          fr: "Passes multiples",
        }),
        numberPrecision: t({
          en: "Number precision",
          zh: "数字精度",
          ko: "숫자 정밀도",
          de: "Zahlenpräzision",
          fr: "Précision numérique",
        }),
        transformPrecision: t({
          en: "Transform precision",
          zh: "变换精度",
          ko: "변환 정밀도",
          de: "Transformationspräzision",
          fr: "Précision de transformation",
        }),
      },
      features: {
        title: t({
          en: "Features",
          zh: "功能",
          ko: "기능",
          de: "Funktionen",
          fr: "Fonctionnalités",
        }),
        resetAll: t({
          en: "Reset all",
          zh: "重置全部",
          ko: "모두 재설정",
          de: "Alle zurücksetzen",
          fr: "Tout réinitialiser",
        }),
      },
      export: {
        title: t({
          en: "Export",
          zh: "导出",
          ko: "내보내기",
          de: "Exportieren",
          fr: "Exporter",
        }),
        png: t({
          en: "Export as PNG",
          zh: "导出为 PNG",
          ko: "PNG로 내보내기",
          de: "Als PNG exportieren",
          fr: "Exporter en PNG",
        }),
        jpeg: t({
          en: "Export as JPEG",
          zh: "导出为 JPEG",
          ko: "JPEG로 내보내기",
          de: "Als JPEG exportieren",
          fr: "Exporter en JPEG",
        }),
        webp: t({
          en: "Export as WebP",
          zh: "导出为 WebP",
          ko: "WebP로 내보내기",
          de: "Als WebP exportieren",
          fr: "Exporter en WebP",
        }),
        ico: t({
          en: "Export as ICO",
          zh: "导出为 ICO",
          ko: "ICO로 내보내기",
          de: "Als ICO exportieren",
          fr: "Exporter en ICO",
        }),
        pdf: t({
          en: "Export as PDF",
          zh: "导出为 PDF",
          ko: "PDF로 내보내기",
          de: "Als PDF exportieren",
          fr: "Exporter en PDF",
        }),
        scale: t({
          en: "Scale",
          zh: "比例",
          ko: "비율",
          de: "Maßstab",
          fr: "Échelle",
        }),
        width: t({
          en: "Width",
          zh: "宽度",
          ko: "너비",
          de: "Breite",
          fr: "Largeur",
        }),
        height: t({
          en: "Height",
          zh: "高度",
          ko: "높이",
          de: "Höhe",
          fr: "Hauteur",
        }),
      },
    },
    messages: {
      uploadSuccess: t({
        en: "SVG file uploaded successfully!",
        zh: "SVG 文件上传成功！",
        ko: "SVG 파일이 성공적으로 업로드되었습니다!",
        de: "SVG-Datei erfolgreich hochgeladen!",
        fr: "Fichier SVG téléchargé avec succès !",
      }),
      copySuccess: t({
        en: "Copied to clipboard!",
        zh: "已复制到剪贴板！",
        ko: "クリップボードに복사しました！",
        de: "In die Zwischenablage kopiert!",
        fr: "Copié dans le presse-papiers !",
      }),
      copyError: t({
        en: "Failed to copy to clipboard",
        zh: "复制到剪贴板失败",
        ko: "クリップボードへの복사に失敗しました",
        de: "Kopieren in die Zwischenablage fehlgeschlagen",
        fr: "Échec de la copie dans le presse-papiers",
      }),
      downloadSuccess: t({
        en: "Downloaded successfully!",
        zh: "下载成功！",
        ko: "다운로드が完了しました！",
        de: "Erfolgreich heruntergeladen!",
        fr: "Téléchargé avec succès !",
      }),
      downloadError: t({
        en: "Failed to download file",
        zh: "下载文件失败",
        ko: "ファイルの다운로드に失敗しました",
        de: "Datei-Download fehlgeschlagen",
        fr: "Échec du téléchargement du fichier",
      }),
      exportPngSuccess: t({
        en: "Exported as PNG!",
        zh: "已导出为 PNG！",
        ko: "PNG로 내보내기 완료！",
        de: "Als PNG exportiert!",
        fr: "Exporté en PNG !",
      }),
      exportJpegSuccess: t({
        en: "Exported as JPEG!",
        zh: "已导出为 JPEG！",
        ko: "JPEG로 내보내기 완료！",
        de: "Als JPEG exportiert!",
        fr: "Exporté en JPEG !",
      }),
      exportWebpSuccess: t({
        en: "Exported as WebP!",
        zh: "已导出为 WebP！",
        ko: "WebP로 내보내기 완료！",
        de: "Als WebP exportiert!",
        fr: "Exporté en WebP !",
      }),
      exportIcoSuccess: t({
        en: "Exported as ICO!",
        zh: "已导出为 ICO！",
        ko: "ICO로 내보내기 완료！",
        de: "Als ICO exportiert!",
        fr: "Exporté en ICO !",
      }),
      exportPdfSuccess: t({
        en: "Exported as PDF!",
        zh: "已导出为 PDF！",
        ko: "PDF로 내보내기 완료！",
        de: "Als PDF exportiert!",
        fr: "Exporté en PDF !",
      }),
      exportError: t({
        en: "Failed to export",
        zh: "导出失败",
        ko: "내보내기 실패",
        de: "Export fehlgeschlagen",
        fr: "Échec de l'export",
      }),
      noSvgToExport: t({
        en: "No optimized SVG to export",
        zh: "没有优化的 SVG 可导出",
        ko: "내보낼 최적화된 SVG가 없습니다",
        de: "Keine optimierte SVG zum Exportieren",
        fr: "Aucun SVG optimisé à exporter",
      }),
      invalidSvgFile: t({
        en: "Invalid file. Please select a valid SVG file (.svg).",
        zh: "无效的文件。请选择有效的 SVG 文件 (.svg)。",
        ko: "유효하지 않은 파일입니다. 유효한 SVG 파일(.svg)을 선택해주세요.",
        de: "Ungültige Datei. Bitte wählen Sie eine gültige SVG-Datei (.svg).",
        fr: "Fichier invalide. Veuillez sélectionner un fichier SVG valide (.svg).",
      }),
      fileReadError: t({
        en: "Failed to read file. Please try again.",
        zh: "读取文件失败。请重试。",
        ko: "파일을 읽는 데 실패했습니다. 다시 시도해주세요.",
        de: "Datei konnte nicht gelesen werden. Bitte versuchen Sie es erneut.",
        fr: "Échec de la lecture du fichier. Veuillez réessayer.",
      }),
      invalidSvgStructure: t({
        en: "The file does not contain valid SVG content.",
        zh: "该文件不包含有效的 SVG 内容。",
        ko: "파일에 유효한 SVG 내용이 없습니다.",
        de: "Die Datei enthält keinen gültigen SVG-Inhalt.",
        fr: "Le fichier ne contient pas de contenu SVG valide.",
      }),
    },
    ui: {
      settings: t({
        en: "Settings",
        zh: "设置",
        ko: "설정",
        de: "Einstellungen",
        fr: "Paramètres",
      }),
      originalTab: t({
        en: "Original",
        zh: "原始",
        ko: "원본",
        de: "Original",
        fr: "Original",
      }),
      optimizedTab: t({
        en: "Optimized",
        zh: "已优化",
        ko: "최적화됨",
        de: "Optimiert",
        fr: "Optimisé",
      }),
      codeTab: t({
        en: "Code",
        zh: "代码",
        ko: "코드",
        de: "Code",
        fr: "Code",
      }),
      dataUriTab: t({
        en: "Data URI",
        zh: "Data URI",
        ko: "Data URI",
        de: "Data URI",
        fr: "Data URI",
      }),
      clickToCompress: t({
        en: 'Click "Compress SVG" to optimize',
        zh: '点击"压缩 SVG"进行优化',
        ko: '"SVG 압축"을 클릭하여 최적화하세요',
        de: 'Klicken Sie auf "SVG komprimieren" zum Optimieren',
        fr: 'Cliquez sur "Compresser SVG" pour optimiser',
      }),
      noOptimizedCode: t({
        en: "No optimized code yet",
        zh: "暂无优化代码",
        ko: "아직 최적화된 코드가 없습니다",
        de: "Noch kein optimierter Code",
        fr: "Pas encore de code optimisé",
      }),
    },
  },
} satisfies Dictionary;

export default optimizeContent;
